export const ka = {
  appName: 'BuildMind AI',
  appTagline: 'სამშენებლო პროექტების ინტელექტი',
  openaiConnected: 'OpenAI დაკავშირებულია',
  demoMode: 'დემო AI რეჟიმი',
  refresh: 'განახლება',
  apiError: 'API-სთან ვერ დავუკავშირდი. ტერმინალში გაუშვით: npm run dev',
  portfolioTitle: 'პროექტების პორტფელი',
  sites: (n) => `${n} ობექტი`,

  statsTotalPortfolio: 'საერთო პორტფელი',
  statsDeployed: (v) => `${v} დახარჯული`,
  statsActiveProjects: 'აქტიური პროექტები',
  statsAvgProgress: (p) => `${p}% საშუალო პროგრესი`,
  statsBudgetWatch: 'ბიუჯეტის კონტროლი',
  statsOverSpend: '65%-ზე მეტი დახარჯული',
  statsOnTrack: 'გრაფიკზეა',
  statsAboveHalf: '50%-ზე მეტი დასრულებული',

  complete: 'დასრულებული',
  budget: 'ბიუჯეტი',
  spent: 'დახარჯული',
  spentPct: (p) => `დახარჯული (${p}%)`,
  daysLeft: (d) => `${d} დღე დარჩა`,
  chartBudgetVsSpent: 'ბიუჯეტი vs დახარჯული',
  chartProgressOverTime: 'პროგრესი დროში',
  analyzing: 'AI ანალიზი…',
  runAnalysis: 'AI რისკის ანალიზი',
  analysisError: 'ანალიზი ვერ მოხერხდა. ბექენდი გაშვებულია?',
  aiRiskTitle: 'AI რისკი და პროგნოზი',
  delayRisk: 'დაგვიანების რისკი',
  budgetRisk: 'ბიუჯეტის რისკი',
  prediction: 'პროგნოზი',
  estCompletion: 'სავარაუდო დასრულება',
  onTimeLikelihood: 'დროულად დასრულების ალბათობა',
  keyIssues: 'ძირითადი საკითხები',
  recommendations: 'რეკომენდაციები',

  chartBudget: 'ბიუჯეტი',
  chartSpent: 'დახარჯული',
  chartRemaining: 'დარჩენილი',
  chartProgress: 'პროგრესი',

  chatTitle: 'AI ასისტენტი',
  chatGreeting:
    'გამარჯობა — მე თქვენი სამშენებლო პროექტების ექსპერტი ვარ. კითხვა დასვით გრაფიკზე, ბიუჯეტზე, რისკებზე ან ნებისმიერ პროექტზე.',
  chatThinking: 'ვფიქრობ…',
  chatPlaceholder: 'კითხვა პროექტებზე, რისკებზე, ბიუჯეტზე…',
  chatError: 'ასისტენტთან ვერ დავუკავშირდი. ბექენდი უნდა იყოს ჩართული (პორტი 3001).',
  chatSuggestions: [
    'რომელ პროექტს აქვს ყველაზე მაღალი რისკი?',
    'შეჯამე პორტფელის ბიუჯეტის მდგომარეობა',
    'რას უნდა ვაპრიორიტეტოთ ამ კვირას?',
  ],
};
